---
- name: install mysql
  package:
    name: "{{ mysql_pkg }}"
    state: present
  register: mysql_installed

- name: enable mysql service
  service:
    name: "{{ mysql_service }}"
    enabled: yes

- name: start mysql service
  service:
    name: "{{ mysql_service }}"
    state: started
